### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by jmariondev** [timp87/vault-rpm#1]
Hi @timp87,

I'm interested in using this repo to build a Vault RPM, but I see it's missing a license. Would you mind adding one?

Personally, I'm partial to the Apache 2.0 license (or the MIT license), but you should pick one that matches your own opinion of your software.

GitHub made a site that makes picking a license easier: <https://choosealicense.com/>

Thanks!

**Comment by timp87** [comment]
Well, I didn't think about a license.
I tend to https://en.wikipedia.org/wiki/Unlicense

**Comment by timp87** [comment]
https://github.com/timp87/vault-rpm/commit/88d64161747d9c3a7ce28143df859b7a37b98607
